apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    app: employees

spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees

  template:
    metadata:
      labels:
        app: employees

    spec:
      containers:
        - name: application-container
          image: 332973323638.dkr.ecr.us-east-1.amazonaws.com/application-ecr:latest
          imagePullPolicy: Always
          env:
            - name: DBPWD
              value: arf12345
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "mysql.assign2-db.svc.cluster.local"
            - name: DBUSER
              value: "root"
          ports:
              - containerPort: 8080
