apiVersion: v1
kind: Pod
metadata:
  name: application
spec:
  containers:
    - name: application-container
      image: 
      env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "database.database.svc.cluster.local"
        - name: DBUSER
          value: "root"
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: secret-registry