apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql
    image: 332973323638.dkr.ecr.us-east-1.amazonaws.com/database-ecr:latest 
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: arf12345
    


